name: Deploy Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Frontend to EC2
        uses: appleboy/ssh-action@master

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}

          script: |
              cd /home/ubuntu/Task-Manager

              git pull origin main

              docker stop frontend-container || true
              docker rm frontend-container || true

              docker build -t frontend-app .

              docker run -d \
                --name frontend-container \
                -p 80:80 \
                frontend-app